name: skUtilities
description: An addon for skript that adds conversions, utilities, files and much more.
authors: [ tim740(Original Author), Prorickey ]
website: https://tim740.github.io/
main: uk.tim740.skUtilities.skUtilities
version: ${version}
api-version: "1.20"
dependencies:
  server:
    Skript:
      load: BEFORE